---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-camel-aws
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-camel-azure
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-camel-gcp
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-camel-misc
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-camel-sql
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-camel-social
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-camel-nosql
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-camel-storage
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-debezium-mongodb
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-debezium-mysql
  annotations:
    qontract.recycle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: connector-catalog-debezium-postgres
  annotations:
    qontract.recycle: "true"
